name: Remove API Key and Push To Hidden Branch

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: <script src=\"AIzaSyDaeA4j77KOqMdW3WfIfhXHLDOEUN_Z3Wo\"></script>
          replace: "%GOOGLE_MAPS_KEY%"
          include: "web/**"
          regex: false
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: hiddenKey-ghPages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
        

          
        
