name: Deploy to GitHub Pages

on:
  push:
    # Update branch according from where you will be pushing the code
    # Small change to rebuild
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.ACCESS_TOKEN}}

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Deploy to Jeff's Private Repo, which will create site
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:jeffzheng13/Lost-and-Found-Steelhacks.git
          BRANCH: main
          FOLDER: .
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
